export const TODO_REQUEST_INITIAL = "TODO_REQUEST_INITIAL";
export const TODO_REQUES_SUCCESS = "TODO_SUCCESS";
export const TODO_REQUEST_FAIL = "TODO_FAIL";

export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST";
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS";
export const TODO_ADD_FAIL = "TODO_ADD_FAIL";

export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
